#!/bin/bash

FORCE_RANCHER_GEN_VERSION="7840121/artifacts"

if [ $DOCKER_TAG == "latest" ]; then tag="master"; else tag=$DOCKER_TAG; fi
version_available=$(curl --write-out %{http_code} --silent --output /dev/null https://gitlab.com/adi90x/rancher-gen-rap/builds/artifacts/$tag/browse?job=compile-go)
if [ $version_available == "302" ]; then build_version=artifacts/$tag; else build_version="artifacts/master"; fi
if [ $FORCE_RANCHER_GEN_VERSION != "" ]; then build_version=$FORCE_RANCHER_GEN_VERSION/artifacts; fi

docker build --build-arg VERSION_RANCHER_GEN=$build_version -t $IMAGE_NAME .